# frozen_string_literal: true

# Lets a user clear their own saved Batch Connect form-value cache and
# return to the app that sent them here.
#
# Every app generated by nf2ood links to `/pun/sys/cache_reset/?app_slug=
# <slug>&return_url=<...>` from a "Saved form values" notice (see
# nfcore_ood_template/form.template.erb), and each generated app's form.js
# already implements the client side of the handshake
# (`resetBatchConnectFormOnce`): if it's reloaded with `?cache_reset=1` in
# the URL, it blanks every visible field. This app is the other half - the
# thing that actually deletes the cached values and performs that reload.
#
# Ported from Tufts' Sinatra-based reference implementation
# (https://github.com/TuftsRT/tufts_ood_cache_reset, MIT licensed, see
# LICENSE) to dependency-free Ruby stdlib, since this site's Ruby has
# neither `sinatra` nor `rack` installed as gems and app dirs under
# apps/sys are root-owned (no path to `gem install` into a load path
# Passenger's app process would pick up without also solving that). The
# behavior, security model, and file-naming assumptions are kept the same;
# only the implementation is dependency-free.
#
# Batch Connect caches each app's last-submitted form values, per user, at:
#   ~/ondemand/data/sys/dashboard/batch_connect/cache/<role>_<app_slug>.json
# (see BatchConnect::App#cache_file / #token in the dashboard app - `token`
# is `"sys/<app_slug>"` or `"dev/<app_slug>"`, and `cache_file` replaces the
# `/` with `_` and appends `.json`). Only `password_field` values inside
# that file are encrypted, so no secret/key is ever needed to delete it.
#
# Deletion only ever happens on POST (never on the bare GET this app is
# usually linked with), and only for a filename that's on the whitelist of
# files this process itself discovered under CACHE_DIR - never an arbitrary
# path built from user input.

require 'cgi'
require 'pathname'
require 'time'

class CacheResetApp
  CACHE_DIR = Pathname.new(
    File.join(Dir.home, 'ondemand', 'data', 'sys', 'dashboard', 'batch_connect', 'cache')
  ).freeze

  # usr_<owner>_<slug>.json cache files exist too (see BatchConnect's UsrRouter#token),
  # but every app this utility is linked from is a `sys` app, so sys_/dev_ covers the
  # real cases; matching upstream's choice to leave usr_ out rather than guess an owner.
  FILENAME_PATTERN = /\A(?:sys|dev)_[A-Za-z0-9][A-Za-z0-9_.-]*\.json\z/.freeze
  DEFAULT_RETURN_URL = '/pun/sys/dashboard'

  def call(env)
    method = env['REQUEST_METHOD']
    path = env['PATH_INFO'].to_s
    query = CGI.parse(env['QUERY_STRING'].to_s)

    if method == 'POST' && path.end_with?('/clear')
      body_params = CGI.parse(read_body(env))
      handle_clear(query, body_params)
    else
      render_form(query)
    end
  rescue StandardError => e
    [500, { 'Content-Type' => 'text/plain; charset=utf-8' }, ["cache_reset error: #{e.class}: #{e.message}"]]
  end

  private

  def read_body(env)
    input = env['rack.input']
    return '' unless input

    input.read.to_s
  end

  def param(hash, key)
    hash[key]&.first.to_s
  end

  # --- discovery -----------------------------------------------------

  def available_cache_files
    return [] unless CACHE_DIR.directory?

    Dir.glob(CACHE_DIR.join('*.json').to_s)
       .select { |p| File.file?(p) && !File.symlink?(p) }
       .map { |p| File.basename(p) }
       .select { |name| name.match?(FILENAME_PATTERN) }
       .sort
  end

  def whitelisted?(filename)
    available_cache_files.include?(filename)
  end

  # Resolves filename to a real path inside CACHE_DIR, or nil if it fails any
  # check: not on the freshly-discovered whitelist, escapes CACHE_DIR, or is
  # a symlink. Deliberately re-checks everything rather than trusting a
  # filename round-tripped through a hidden form field.
  def safe_cache_path(filename)
    return nil if filename.nil? || filename.empty?
    return nil unless filename.match?(FILENAME_PATTERN)
    return nil unless whitelisted?(filename)

    candidate = CACHE_DIR.join(filename).expand_path
    return nil unless candidate.dirname == CACHE_DIR.expand_path
    return nil unless candidate.exist?

    st = File.lstat(candidate.to_s)
    return nil unless st.file? && !st.symlink?

    candidate
  rescue Errno::ENOENT, Errno::ENOTDIR
    nil
  end

  # --- return_url handling --------------------------------------------

  def sanitize_return_url(value)
    return nil if value.nil? || value.empty?
    return nil if value.include?("\r") || value.include?("\n")
    return nil if value.include?('://')
    return nil unless value.start_with?('/pun/')

    value
  end

  def resolved_return_url(query, body_params = {})
    sanitize_return_url(param(body_params, 'return_url')) ||
      sanitize_return_url(param(query, 'return_url')) ||
      DEFAULT_RETURN_URL
  end

  # Appends cache_reset=1&cache_reset_at=<epoch> to return_url, which every
  # generated pipeline app's form.js (resetBatchConnectFormOnce) already
  # knows how to consume to blank its visible fields on the way back in.
  def with_cache_reset_flag(url)
    base, fragment = url.split('#', 2)
    path, query_str = base.split('?', 2)
    params = CGI.parse(query_str.to_s)
    params['cache_reset'] = ['1']
    params['cache_reset_at'] = [Time.now.to_i.to_s]
    encoded = params.flat_map { |k, vs| vs.map { |v| "#{CGI.escape(k)}=#{CGI.escape(v)}" } }.join('&')
    rebuilt = "#{path}?#{encoded}"
    rebuilt += "##{fragment}" if fragment
    rebuilt
  end

  # --- preferred selection ---------------------------------------------

  # When arriving via ?app_slug=..., pre-selects that app's own cache file
  # in the dropdown instead of making the user hunt for it.
  def preferred_filename(query)
    app_slug = param(query, 'app_slug')
    return '' if app_slug.empty?

    exact = %w[sys dev].map { |role| "#{role}_#{app_slug}.json" }.find { |f| whitelisted?(f) }
    return exact if exact

    available_cache_files.find { |f| f.end_with?("_#{app_slug}.json") } || ''
  end

  # --- rendering ---------------------------------------------------------

  def h(value)
    CGI.escapeHTML(value.to_s)
  end

  def render_form(query, status: nil, message: nil)
    files = available_cache_files
    selected = preferred_filename(query)
    return_url = resolved_return_url(query)
    app_slug = param(query, 'app_slug')

    # Arriving fresh (not a post-action redisplay) via ?app_slug=... that
    # resolves to exactly one cache file gets a single-app confirm screen
    # instead of a dropdown over every cached app - see show_all_link for
    # the escape hatch back to the full list. GET never deletes anything
    # either way; this only changes which form is shown.
    focused = status.nil? && param(query, 'show_all') != '1' && !selected.empty?

    status_html = status && message ? %(<p class="status #{h(status)}">#{h(message)}</p>) : ''

    body_html =
      if files.empty?
        %(<p class="status warning">No saved form caches found in <code>#{h(CACHE_DIR)}</code>.</p>)
      elsif focused
        render_focused(selected, return_url, app_slug, query)
      else
        render_picker(files, selected, return_url, app_slug)
      end

    html = <<~HTML
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Reset saved form values</title>
        <style>#{STYLE}</style>
      </head>
      <body>
        <main class="panel">
          <h1>Reset saved form values</h1>
          <p>Open OnDemand remembers what you last typed into a pipeline's form. Clear that here if it's showing stale defaults.</p>
          #{status_html}
          #{body_html}
        </main>
      </body>
      </html>
    HTML

    [200, { 'Content-Type' => 'text/html; charset=utf-8' }, [html]]
  end

  # Single-app confirm screen, used when app_slug resolves to exactly one
  # cache file. Still POST-to-delete - this only skips the dropdown.
  def render_focused(filename, return_url, app_slug, query)
    <<~HTML
      <p>Ready to clear the saved form cache for <strong>#{h(app_slug)}</strong>:</p>
      <p><code>#{h(filename)}</code></p>
      <form method="post" action="clear">
        <input type="hidden" name="cache_file" value="#{h(filename)}">
        <input type="hidden" name="return_url" value="#{h(return_url)}">
        <input type="hidden" name="app_slug" value="#{h(app_slug)}">
        <div class="actions">
          <button type="submit" name="return_after" value="1">Clear and return</button>
          <button type="submit" class="secondary">Clear only</button>
          <a class="secondary" href="#{h(return_url)}">Cancel</a>
        </div>
      </form>
      <p class="helper"><a href="#{h(show_all_link(query))}">Clear a different app's cache instead</a></p>
    HTML
  end

  # Dropdown over every cache file this user has. Shown when there's no
  # single-app match (bare dashboard launch), when the user asked for it
  # via show_all=1, or when redisplaying after a clear/error.
  def render_picker(files, selected, return_url, app_slug)
    options = files.map do |f|
      sel = f == selected ? ' selected' : ''
      %(<option value="#{h(f)}"#{sel}>#{h(f)}</option>)
    end.join
    <<~HTML
      <form method="post" action="clear">
        <label for="cache_file">Saved form cache to clear</label>
        <select id="cache_file" name="cache_file" required>#{options}</select>
        <input type="hidden" name="return_url" value="#{h(return_url)}">
        <input type="hidden" name="app_slug" value="#{h(app_slug)}">
        <div class="actions">
          <button type="submit" name="return_after" value="1">Clear and return</button>
          <button type="submit" class="secondary">Clear only</button>
          <a class="secondary" href="#{h(return_url)}">Back without clearing</a>
        </div>
      </form>
    HTML
  end

  # Preserves app_slug/return_url while dropping into the full-list picker -
  # a plain GET link, so it's safe (no side effect) to click.
  def show_all_link(query)
    app_slug = param(query, 'app_slug')
    return_url_raw = param(query, 'return_url')
    parts = []
    parts << "app_slug=#{CGI.escape(app_slug)}" unless app_slug.empty?
    parts << "return_url=#{CGI.escape(return_url_raw)}" unless return_url_raw.empty?
    parts << 'show_all=1'
    "?#{parts.join('&')}"
  end

  STYLE = <<~CSS
    body { font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; background: #f5f7f4; margin: 0; padding: 3rem 1rem; }
    .panel { max-width: 40rem; margin: 0 auto; background: #fff; border: 1px solid #d8ded9; border-radius: 10px; padding: 2rem; }
    h1 { margin-top: 0; font-size: 1.4rem; }
    select { width: 100%; padding: .5rem; margin: .5rem 0 1rem; border-radius: 6px; border: 1px solid #c8cfc9; }
    .actions { display: flex; flex-wrap: wrap; gap: .6rem; align-items: center; }
    button, a.secondary { padding: .55rem .9rem; border-radius: 6px; border: 1px solid #1e5d3b; text-decoration: none; font-weight: 600; cursor: pointer; font-size: .95rem; }
    button { background: #1e5d3b; color: #fff; }
    button.secondary, a.secondary { background: #fff; color: #1e5d3b; }
    .status { padding: .7rem .9rem; border-radius: 6px; }
    .status.success { background: #e8f5eb; color: #174b27; }
    .status.warning { background: #fff4db; color: #7a5b00; }
    .status.error { background: #fde8e8; color: #8a1c1c; }
    .helper { margin-top: 1rem; font-size: .85rem; }
    .helper a { color: #1e5d3b; }
  CSS

  # --- clear action -----------------------------------------------------

  def handle_clear(query, body_params)
    filename = param(body_params, 'cache_file')
    return_after = param(body_params, 'return_after') == '1'
    return_url = resolved_return_url(query, body_params)

    path = safe_cache_path(filename)
    return render_form(query, status: 'error', message: 'That cache file is not available to clear.') if path.nil?

    begin
      File.delete(path.to_s)
    rescue Errno::ENOENT
      # Already gone - the end state the user wants is achieved either way.
    end

    if return_after
      [302, { 'Location' => with_cache_reset_flag(return_url) }, []]
    else
      render_form(query, status: 'success', message: "Cleared #{filename}.")
    end
  end
end
